"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "path"
  style = "plain"
  background = "transparent"
  foreground = "p:prompt-fg"
  template = "{{ .Path }}"

    [blocks.segments.properties]
    style = "full"

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "p:gitstatus"
  background = "transparent"
  template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
    branch_icon = ""
    commit_icon = "@"
    fetch_status = true
    fetch_upstream_icon = true

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

  [[blocks.segments]]
  type = 'executiontime'
  style = 'plain'
  foreground = 'p:timer'
  background = 'transparent'
  template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
    threshold = 1000

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground_templates = [
    "{{ if gt .Code 0}}p:error{{end}}",
    "{{ if eq .Code 0}}p:cursor{{end}}"
  ]
  background = "transparent"
  foreground = "p:cursor"
  template = ""

[transient_prompt]
background = "transparent"
foreground = "p:cursor"
foreground_templates = [
  "{{ if gt .Code 0}}p:error{{end}}",
  "{{ if eq .Code 0}}p:cursor{{end}}"
]
template = " "

[palette]
prompt-fg = "blue"
cursor = "magenta"
error = "red"
gitstatus = "#45475a"
timer = "#fab387"
